SELECT ROTULO, COUNT(1) AS VALOR1,0 AS VALOR2, 0 AS VALOR3, 0 AS VALOR4, 0 AS VALOR5\nFROM(\nSELECT M_LPA_DISCAP.XDESCRIPCION AS ROTULO,\n       M_LPA.TIPO_IDENTIF,\n       M_LPA_TIPO_IDENTIF.XDESCRIPCION AS NOMBRE_TIPO_IDENTIF,\n       M_LPA.NUM_IDENTIF\nFROM M_LPA\nLEFT JOIN M_LPA_TIPO_IDENTIF ON (M_LPA_TIPO_IDENTIF.TIPO_IDENTIF_ID = M_LPA.TIPO_IDENTIF)\nLEFT JOIN M_LPA_DISCAP ON (M_LPA_DISCAP.DISCAP_ID = M_LPA.DISCAP_ID)\nWHERE M_LPA.FECHA_ACTIV BETWEEN '2020-01-01' AND '2024-04-08' AND\n           M_LPA.DEPARTAMENTO LIKE '%%'\nGROUP BY ROTULO,TIPO_IDENTIF,NOMBRE_TIPO_IDENTIF,NUM_IDENTIF\n)\nGROUP BY ROTULO

SELECT 
    \"ROTULO\", 
    COUNT(1) AS \"VALOR1\",
    0 AS \"VALOR2\", 
    0 AS \"VALOR3\", 
    0 AS \"VALOR4\", 
    0 AS \"VALOR5\" 
FROM( 
    SELECT 
        M_LPA_DISCAP.XDESCRIPCION AS ROTULO, 
           
        \"M_LPAS\".\"FK_LPA_PERSONA\" AS \"TIPO_IDENTIF\",                 
        \"M_LPA_PERSONAS\".\"TIPO_DOCUMENTO\" AS \"NOMBRE_TIPO_IDENTIF\",            
        \"M_LPA_PERSONAS\".\"DOCUMENTO\" AS \"NUM_IDENTIF\"       
    FROM
        M_LPA 

    LEFT JOIN M_LPA_DISCAP ON (M_LPA_DISCAP.DISCAP_ID = M_LPA.DISCAP_ID) 
    LEFT JOIN \"M_LPA_PERSONAS\" ON (\"M_LPA_PERSONAS\".\"ID\" = \"M_LPAS\".\"FK_LPA_PERSONA\")         
    
    WHERE 
        M_LPA.FECHA_ACTIV BETWEEN '2020-01-01' AND '2024-04-08' AND 
        M_LPA.DEPARTAMENTO LIKE '%%' 
    GROUP BY 
        ROTULO,TIPO_IDENTIF,NOMBRE_TIPO_IDENTIF,NUM_IDENTIF 
)
GROUP BY ROTULO