--00142 LPA - PERSONAS ATENDIDAS POR MES
SELECT ROTULO, COUNT(1) AS VALOR1,0 AS VALOR2, 0 AS VALOR3, 0 AS VALOR4, 0 AS VALOR5\nFROM(\nSELECT EXTRACT(YEAR FROM M_LPA.FECHA_ATENCION)||'-'||\n       CASE\n          WHEN EXTRACT (MONTH FROM M_LPA.FECHA_ATENCION)= '01' THEN 'ENERO'\n          WHEN EXTRACT (MONTH FROM M_LPA.FECHA_ATENCION)= '02' THEN 'FEBRERO'\n          WHEN EXTRACT (MONTH FROM M_LPA.FECHA_ATENCION)= '03' THEN 'MARZO'\n          WHEN EXTRACT (MONTH FROM M_LPA.FECHA_ATENCION)= '04' THEN 'ABRIL'\n          WHEN EXTRACT (MONTH FROM M_LPA.FECHA_ATENCION)= '05' THEN 'MAYO'\n          WHEN EXTRACT (MONTH FROM M_LPA.FECHA_ATENCION)= '06' THEN 'JUNIO'\n          WHEN EXTRACT (MONTH FROM M_LPA.FECHA_ATENCION)= '07' THEN 'JULIO'\n          WHEN EXTRACT (MONTH FROM M_LPA.FECHA_ATENCION)= '08' THEN 'AGOSTO'\n          WHEN EXTRACT (MONTH FROM M_LPA.FECHA_ATENCION)= '09' THEN 'SEPTIEMBRE'\n          WHEN EXTRACT (MONTH FROM M_LPA.FECHA_ATENCION)= '10' THEN 'OCTUBRE'\n          WHEN EXTRACT (MONTH FROM M_LPA.FECHA_ATENCION)= '11' THEN 'NOVIEMBRE'\n          WHEN EXTRACT (MONTH FROM M_LPA.FECHA_ATENCION)= '12' THEN 'DICIEMBRE'\n      END AS ROTULO,\n      M_LPA.TIPO_IDENTIF,\n      M_LPA_TIPO_IDENTIF.XDESCRIPCION AS NOMBRE_TIPO_IDENTIF,\n      M_LPA.NUM_IDENTIF\nFROM M_LPA\nLEFT JOIN M_LPA_TIPO_IDENTIF ON (M_LPA_TIPO_IDENTIF.TIPO_IDENTIF_ID = M_LPA.TIPO_IDENTIF)\nWHERE M_LPA.FECHA_ATENCION BETWEEN '2020-01-01' AND '2024-04-08' AND\n           M_LPA.DEPARTAMENTO LIKE '%%'\nGROUP BY ROTULO,TIPO_IDENTIF,NOMBRE_TIPO_IDENTIF,NUM_IDENTIF\n)\nGROUP BY ROTULO

SELECT 
    \"ROTULO\", 
    COUNT(1) AS \"VALOR1\",
    0 AS \"VALOR2\", 
    0 AS \"VALOR3\", 
    0 AS \"VALOR4\", 
    0 AS \"VALOR5\" 
FROM(
    SELECT EXTRACT(YEAR FROM \"M_LPAS\".\"FECHA_ATENCION\")||'-'||
        CASE
            WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '01' THEN 'ENERO'
            WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '02' THEN 'FEBRERO'
            WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '03' THEN 'MARZO'
            WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '04' THEN 'ABRIL'
            WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '05' THEN 'MAYO'
            WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '06' THEN 'JUNIO'
            WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '07' THEN 'JULIO'
            WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '08' THEN 'AGOSTO'
            WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '09' THEN 'SEPTIEMBRE'
            WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '10' THEN 'OCTUBRE'
            WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '11' THEN 'NOVIEMBRE'
            WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '12' THEN 'DICIEMBRE'
        END AS \"ROTULO\",
        \"M_LPAS\".\"FK_LPA_PERSONA\" AS \"TIPO_IDENTIF\",     
        \"M_LPA_PERSONAS\".\"TIPO_DOCUMENTO\" AS \"NOMBRE_TIPO_IDENTIF\",  
        \"M_LPA_PERSONAS\".\"DOCUMENTO\" AS \"NUM_IDENTIF\"  
    FROM 
        \"M_LPAS\"
    LEFT JOIN \"M_LPA_PERSONAS\" ON (\"M_LPA_PERSONAS\".\"ID\" = \"M_LPAS\".\"FK_LPA_PERSONA\") 
    LEFT JOIN \"M_LPA_EMERGENCIAS\" ON (\"M_LPA_EMERGENCIAS\".\"ID\" = \"M_LPAS\".\"FK_LPA_EMERGENCIA\")   
    WHERE 
        \"M_LPAS\".\"FECHA_ATENCION\" BETWEEN '2020-01-01' AND '2024-04-08' AND
        \"M_LPA_EMERGENCIAS\".\"DEPARTAMENTO\" LIKE '%%'
    GROUP BY 
        \"ROTULO\",\"TIPO_IDENTIF\",\"NOMBRE_TIPO_IDENTIF\",\"NUM_IDENTIF\"
) as x
GROUP BY \"ROTULO\"


SELECT      \"ROTULO\",      COUNT(1) AS \"VALOR1\",     0 AS \"VALOR2\",      0 AS \"VALOR3\",      0 AS \"VALOR4\",      0 AS \"VALOR5\"  FROM(     SELECT EXTRACT(YEAR FROM \"M_LPAS\".\"FECHA_ATENCION\")||'-'||         CASE             WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '01' THEN 'ENERO'             WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '02' THEN 'FEBRERO'             WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '03' THEN 'MARZO'             WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '04' THEN 'ABRIL'             WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '05' THEN 'MAYO'             WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '06' THEN 'JUNIO'             WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '07' THEN 'JULIO'             WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '08' THEN 'AGOSTO'             WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '09' THEN 'SEPTIEMBRE'             WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '10' THEN 'OCTUBRE'             WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '11' THEN 'NOVIEMBRE'             WHEN EXTRACT (MONTH FROM \"M_LPAS\".\"FECHA_ATENCION\")= '12' THEN 'DICIEMBRE'         END AS \"ROTULO\",         \"M_LPAS\".\"FK_LPA_PERSONA\" AS \"TIPO_IDENTIF\",              \"M_LPA_PERSONAS\".\"TIPO_DOCUMENTO\" AS \"NOMBRE_TIPO_IDENTIF\",           \"M_LPA_PERSONAS\".\"DOCUMENTO\" AS \"NUM_IDENTIF\"       FROM          \"M_LPAS\"     LEFT JOIN \"M_LPA_PERSONAS\" ON (\"M_LPA_PERSONAS\".\"ID\" = \"M_LPAS\".\"FK_LPA_PERSONA\")      LEFT JOIN \"M_LPA_EMERGENCIAS\" ON (\"M_LPA_EMERGENCIAS\".\"ID\" = \"M_LPAS\".\"FK_LPA_EMERGENCIA\")        WHERE          \"M_LPAS\".\"FECHA_ATENCION\" BETWEEN '2020-01-01' AND '2024-04-08' AND         \"M_LPA_EMERGENCIAS\".\"DEPARTAMENTO\" LIKE '%%'     GROUP BY          \"ROTULO\",\"TIPO_IDENTIF\",\"NOMBRE_TIPO_IDENTIF\",\"NUM_IDENTIF\" ) as x GROUP BY \"ROTULO\"
SELECT      "ROTULO",      COUNT(1) AS "VALOR1",     0 AS "VALOR2",      0 AS "VALOR3",      0 AS "VALOR4",      0 AS "VALOR5"  FROM(     SELECT EXTRACT(YEAR FROM "M_LPAS"."FECHA_ATENCION")||'-'||         CASE             WHEN EXTRACT (MONTH FROM "M_LPAS"."FECHA_ATENCION")= '01' THEN 'ENERO'             WHEN EXTRACT (MONTH FROM "M_LPAS"."FECHA_ATENCION")= '02' THEN 'FEBRERO'             WHEN EXTRACT (MONTH FROM "M_LPAS"."FECHA_ATENCION")= '03' THEN 'MARZO'             WHEN EXTRACT (MONTH FROM "M_LPAS"."FECHA_ATENCION")= '04' THEN 'ABRIL'             WHEN EXTRACT (MONTH FROM "M_LPAS"."FECHA_ATENCION")= '05' THEN 'MAYO'             WHEN EXTRACT (MONTH FROM "M_LPAS"."FECHA_ATENCION")= '06' THEN 'JUNIO'             WHEN EXTRACT (MONTH FROM "M_LPAS"."FECHA_ATENCION")= '07' THEN 'JULIO'             WHEN EXTRACT (MONTH FROM "M_LPAS"."FECHA_ATENCION")= '08' THEN 'AGOSTO'             WHEN EXTRACT (MONTH FROM "M_LPAS"."FECHA_ATENCION")= '09' THEN 'SEPTIEMBRE'             WHEN EXTRACT (MONTH FROM "M_LPAS"."FECHA_ATENCION")= '10' THEN 'OCTUBRE'             WHEN EXTRACT (MONTH FROM "M_LPAS"."FECHA_ATENCION")= '11' THEN 'NOVIEMBRE'             WHEN EXTRACT (MONTH FROM "M_LPAS"."FECHA_ATENCION")= '12' THEN 'DICIEMBRE'         END AS "ROTULO",         "M_LPAS"."FK_LPA_PERSONA" AS "TIPO_IDENTIF",              "M_LPA_PERSONAS"."TIPO_DOCUMENTO" AS "NOMBRE_TIPO_IDENTIF",           "M_LPA_PERSONAS"."DOCUMENTO" AS "NUM_IDENTIF"       FROM          "M_LPAS"     LEFT JOIN "M_LPA_PERSONAS" ON ("M_LPA_PERSONAS"."ID" = "M_LPAS"."FK_LPA_PERSONA")      LEFT JOIN "M_LPA_EMERGENCIAS" ON ("M_LPA_EMERGENCIAS"."ID" = "M_LPAS"."FK_LPA_EMERGENCIA")        WHERE          "M_LPAS"."FECHA_ATENCION" BETWEEN '2020-01-01' AND '2024-04-08' AND         "M_LPA_EMERGENCIAS"."DEPARTAMENTO" LIKE '%%'     GROUP BY          "ROTULO","TIPO_IDENTIF","NOMBRE_TIPO_IDENTIF","NUM_IDENTIF" ) as x GROUP BY "ROTULO"
