SELECT count(*) FROM "M_KOBO_FORMULARIOS"   LIMIT 1  --where "FECHA" <= '2025-07-29'
SELECT count(*) FROM "M_KOBO_RESPUESTAS" where "FECHA" >= '2025-07-29'  LIMIT 1 
SELECT count(*) FROM "M_FORMULARIOS"
delete from "M_KOBO_FORMULARIOS" LIMIT 10000
