FROM php:7.3-fpm

# Copy composer.lock and composer.json
#COPY composer.lock composer.json /var/www/
COPY . /var/www/html

# Set working directory
WORKDIR /var/www/html

# Install dependencies

RUN curl -sL https://deb.nodesource.com/setup_12.x

RUN apt-get update && apt-get install -y \
    libzip-dev \
    libmcrypt-dev \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install extensions
 RUN docker-php-ext-install zip 
#pdo_mysql mbstring exif pcntl
RUN docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/
 RUN docker-php-ext-install gd

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Copy existing application directory permissions
COPY --chown=www:www . /var/www/html
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# Change current user to www
USER www
# chown -R "$(id -un)" "$(composer config --global home)"
# RUN chown -R testuser:testuser /var/local/testrunner/logs

RUN chown -R "$(id -un)" "$(composer config --global home)"
# sudo chown -R $USER ~/.composer/
RUN chown -R www ~/.composer/

RUN composer install

# Expose port 9000 and start php-fpm server
EXPOSE 80

#echo "Caching config..."
RUN php artisan config:cache

# echo "Caching routes..."
RUN php artisan route:cache

CMD [ "php", "./public/index.php" ]

#CMD ["php", "artisan", "serve"]

#CMD ["php-fpm"]