set PATH="C:\Program Files\Firebird\Firebird_2_5\bin:$PATH"
connect "/opt/lampp/firebird/db/ach.gdb" user 'SYSDBA' password 'masterkey';
CONNECT "C:\opt\lampp\firebird\db\ach.gdb" user 'SYSDBA' password 'masterkey';





la idea es filtarr para intentar optener por like datos delos formiularios

SELECT * FROM V_M_KOBO_RESPUESTAS WHERE ID_M_KOBO_FORMULARIOS ='{IDX}' AND 
    ID_P_FORMULARIOS IN ('001428','001427','001429','001472','001473','001475','001476','001577','001486','001484','001485') 
    ORDER BY POSICION_GRUPO,POSICION,XROTULO,XROTULO_PLANTILLA


SELECT * FROM V_M_KOBO_RESPUESTAS WHERE ROTULO like '%energia%' or VALOR like '%energia%' ;

ORDER BY POSICION_GRUPO,POSICION,XROTULO,XROTULO_PLANTILLA

SELECT      V_M_KOBO_RESPUESTAS.*, 
	CAST(SUBSTRING(VALOR FROM 1 FOR 32000) AS VARCHAR(32000)) AS VALOR_COMPLETE
FROM        V_M_KOBO_RESPUESTAS
 WHERE ROTULO like '%energia%' or VALOR like '%energia%' ;



SELECT      
    V_M_KOBO_RESPUESTAS.*,
    CAST(SUBSTRING(VALOR FROM 1 FOR 32000) AS VARCHAR(32000)) AS VALOR_COMPLETE
FROM        
    V_M_KOBO_RESPUESTAS
WHERE 
    ROTULO LIKE '%energia%' OR 
    VALOR LIKE '%energia%' OR
    ROTULO LIKE '%Energia%' OR 
    VALOR LIKE '%Energia%' OR
    ROTULO LIKE '%ENERGIA%' OR 
    VALOR LIKE '%ENERGIA%' ;

    

SELECT      
    V_M_KOBO_RESPUESTAS.*,
    CAST(SUBSTRING(VALOR FROM 1 FOR 32000) AS VARCHAR(32000)) AS VALOR_COMPLETE
FROM        
    V_M_KOBO_RESPUESTAS
WHERE 
    ROTULO LIKE '%agua%' OR 
    VALOR LIKE '%agua%' OR
    ROTULO LIKE '%Agua%' OR 
    VALOR LIKE '%Agua%' OR
    ROTULO LIKE '%AGUA%' OR 
    VALOR LIKE '%AGUA%' ;

--QUERY PARA SABER PARA QUE SON LOS P_FORMULARIOS
SELECT * FROM P_FORMULARIOS WHERE ID_P_FORMULARIOS IN (001238, 001253, 001198, 001721, 001313, 001285, 001292, 001293);



-- query para ver las coincidencias de ern
--    P_FORMULARIOS.ID_P_FORMULARIOS IN (001238, 001253, 001198, 001721, 001313, 001285, 001292, 001293) AND


SELECT M_KOBO_RESPUESTAS.ID_M_KOBO_RESPUESTAS AS ID_M_KOBO_RESPUESTAS,
       M_KOBO_RESPUESTAS.ID_M_USUARIOS AS ID_M_USUARIOS,
       M_KOBO_RESPUESTAS.FECHA AS FECHA,
       M_KOBO_RESPUESTAS.FECHA_REGISTRO AS FECHA_REGISTRO,
       M_KOBO_RESPUESTAS.ID AS ID,
       M_KOBO_RESPUESTAS.ESTATUS AS ESTATUS,
       M_KOBO_RESPUESTAS.ID_M_KOBO_FORMULARIOS AS ID_M_KOBO_FORMULARIOS,
       M_KOBO_RESPUESTAS.ID_M_FORMULARIOS AS ID_M_FORMULARIOS,
       M_KOBO_RESPUESTAS.ID_P_FORMULARIOS AS ID_P_FORMULARIOS,
       M_KOBO_RESPUESTAS.TIPO AS TIPO,
       M_KOBO_RESPUESTAS.ROTULO AS ROTULO, 
       M_KOBO_RESPUESTAS.VALOR_C AS VALOR_C, 
       M_KOBO_RESPUESTAS.VALOR_N AS VALOR_N,
       M_KOBO_RESPUESTAS.VALOR AS VALOR, 
       M_KOBO_RESPUESTAS.REFERENCIA AS REFERENCIA,
       M_KOBO_RESPUESTAS.UID AS UID,
       M_KOBO_RESPUESTAS.FUID AS FUID,
       M_KOBO_RESPUESTAS.ID_TMP_RESPUESTAS AS ID_TMP_RESPUESTAS,
       M_KOBO_RESPUESTAS.XROTULO AS XROTULO, 
       M_KOBO_RESPUESTAS.XVALOR AS XVALOR, 

       P_FORMULARIOS.ROTULO AS ROTULO_PLANTILLA, 
       UPPER(P_FORMULARIOS.ROTULO)  AS XROTULO_PLANTILLA, 

       P_FORMULARIOS.XGRUPO AS XGRUPO,
       P_FORMULARIOS.POSICION as POSICION,
       P_FORMULARIOS.POSICION_GRUPO as POSICION_GRUPO,
       M_KOBO_FORMULARIOS.MUNICIPIO AS MUNICIPIO,
       M_KOBO_FORMULARIOS.DEPARTAMENTO AS DEPARTAMENTO,
       M_KOBO_FORMULARIOS.REGION AS REGION,
       M_FORMULARIOS.NOMBRES AS NOMBRE_FORMULARIO,
       M_KOBO_FORMULARIOS.XCODIGO_ALERTA AS XCODIGO_ALERTA,
       M_KOBO_FORMULARIOS.FECHA_ESTADISTICA AS FECHA_ESTADISTICA,
       M_KOBO_FORMULARIOS.FECHA_FORMULARIO AS FECHA_FORMULARIO

FROM M_KOBO_RESPUESTAS
LEFT JOIN M_KOBO_FORMULARIOS ON (M_KOBO_FORMULARIOS.ID_M_KOBO_FORMULARIOS = M_KOBO_RESPUESTAS.ID_M_KOBO_FORMULARIOS)
LEFT JOIN M_FORMULARIOS      ON (M_FORMULARIOS.ID_M_FORMULARIOS = M_KOBO_FORMULARIOS.ID_M_FORMULARIOS)
INNER JOIN P_FORMULARIOS      ON (P_FORMULARIOS.ID_P_FORMULARIOS = M_KOBO_RESPUESTAS.ID_P_FORMULARIOS)
WHERE P_FORMULARIOS.ESTATUS = 'ACT' AND
    M_FORMULARIOS.ID_M_FORMULARIOS = 0012 AND

    M_KOBO_RESPUESTAS.ROTULO LIKE '%sospecha%' OR M_KOBO_RESPUESTAS.VALOR LIKE '%sospecha%' OR  M_KOBO_RESPUESTAS.ROTULO LIKE '%Sospecha%' OR    M_KOBO_RESPUESTAS.VALOR LIKE '%Sospecha%' OR    M_KOBO_RESPUESTAS.ROTULO LIKE '%SOSPECHA%' OR    M_KOBO_RESPUESTAS.VALOR LIKE '%SOSPECHA%' OR
    
    M_KOBO_RESPUESTAS.ROTULO LIKE '%accidentes%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%accidentes%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%Accidentes%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%Accidentes%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%ACCIDENTES%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%ACCIDENTES%' OR
    
    M_KOBO_RESPUESTAS.ROTULO LIKE '%incidentes%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%incidentes%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%Incidentes%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%Incidentes%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%INCIDENTES%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%INCIDENTES%' OR
    
    M_KOBO_RESPUESTAS.ROTULO LIKE '%camino%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%camino%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%Camino%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%Camino%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%CAMINO%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%CAMINO%' OR
    
    M_KOBO_RESPUESTAS.ROTULO LIKE '%sospecha%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%sospecha%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%Sospecha%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%Sospecha%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%SOSPECHA%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%SOSPECHA%' OR
    
    M_KOBO_RESPUESTAS.ROTULO LIKE '%minas%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%minas%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%Minas%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%Minas%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%MINAS%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%MINAS%' OR

    M_KOBO_RESPUESTAS.ROTULO LIKE '%desminado%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%desminado%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%Desminado%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%Desminado%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%DESMINADO%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%DESMINADO%' OR

    M_KOBO_RESPUESTAS.ROTULO LIKE '%municion%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%municion%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%Municion%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%Municion%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%MUNICION%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%MUNICION%' OR
    
    M_KOBO_RESPUESTAS.ROTULO LIKE '%sin explosionar%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%sin explosionar%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%Sin Explosionar%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%Sin Explosionar%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%SIN EXPLOSIONAR%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%SIN EXPLOSIONAR%' OR

    
    M_KOBO_RESPUESTAS.ROTULO LIKE '%desminado humanitario%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%desminado humanitario%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%Desminado Humanitario%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%Desminado Humanitario%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%DESMINADO HUMANITARIO%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%DESMINADO HUMANITARIO%' OR

    
    M_KOBO_RESPUESTAS.ROTULO LIKE '%map%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%map%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%Map%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%Map%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%MAP%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%MAP%' OR

    
    
    M_KOBO_RESPUESTAS.ROTULO LIKE '%minado%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%minado%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%Minado%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%Minado%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%MINADO%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%MINADO%' OR

    
    M_KOBO_RESPUESTAS.ROTULO LIKE '%muse%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%muse%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%Muse%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%Muse%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%MUSE%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%MUSE%' OR

    
    
    M_KOBO_RESPUESTAS.ROTULO LIKE '%explosivo%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%explosivo%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%Explosivo%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%Explosivo%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%EXPLOSIVO%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%EXPLOSIVO%' OR

    
    
    M_KOBO_RESPUESTAS.ROTULO LIKE '%victima%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%victima%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%Victima%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%Victima%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%VICTIMA%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%VICTIMA%' OR

    
    M_KOBO_RESPUESTAS.ROTULO LIKE '%municiones sin explosionar%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%municiones sin explosionar%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%Municiones sin explosionar%' OR
    M_KOBO_RESPUESTAS.ROTULO LIKE '%Municiones sin explosionar%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%MUNICIONES SIN EXPLOTAR%' OR
    M_KOBO_RESPUESTAS.VALOR LIKE '%MUNICIONES SIN EXPLOTAR%';





