--ON M_KOBO_RESPUESTAS on insert

BEGIN
  /* Trigger body */


  IF(NEW.ID_P_FORMULARIOS ='001473') THEN
  BEGIN
       XVALOR = '' ;
       IF( NEW.XVALOR = 'REQUERIMIENTO INDIVIDUAL POR VBG'  AND :XVALOR='')  THEN XVALOR = 'VBG-';
       IF( NEW.XVALOR = 'NNAJ'  AND :XVALOR='')  THEN XVALOR = 'NNAJ-';
       IF( NEW.XVALOR = 'PR'  AND :XVALOR='')  THEN XVALOR = 'PR-';
       IF( XVALOR='')  THEN XVALOR = '';

       XVALOR = TRIM(:XVALOR);

       --EXCEPTION E_DEBUG XVALOR;
       UPDATE M_KOBO_FORMULARIOS SET PREFIJO_ALERTA= :XVALOR WHERE ID_M_KOBO_FORMULARIOS = NEW.ID_M_KOBO_FORMULARIOS;

  END

  -- PARA UN FORMULARIO DE PERFIL TERRITORIAL SE DEFINE EL prefijo anFYtJMm6iFs55vrnsBtN8
  IF( NEW.ID_M_FORMULARIOS = '001121') THEN
  BEGIN
       XVALOR = '' ;
       IF( XVALOR='')  THEN XVALOR = 'RT-';

       XVALOR = TRIM(:XVALOR);

       --EXCEPTION E_DEBUG XVALOR;
       UPDATE M_KOBO_FORMULARIOS SET PREFIJO_ALERTA= :XVALOR WHERE ID_M_KOBO_FORMULARIOS = NEW.ID_M_KOBO_FORMULARIOS;

  END

END