select RDB$TRIGGER_NAME, RDB$RELATION_NAME, RDB$TRIGGER_SOURCE from rdb$TRIGGERS where rdb$TRIGGER_NAME = 'T_KOBO_RESPUESTAS'


            "RDB$TRIGGER_SOURCE": "AS\r\nDECLARE VARIABLE XID_M_KOBO_FORMULARIOS VARCHAR(16);\r\nDECLARE VARIABLE \"ROW_COUNT\" INTEGER;\r\nDECLARE VARIABLE XESTATUS VARCHAR(20);\r\nDECLARE VARIABLE XROTULO VARCHAR(5000);\r\nBEGIN\r\n--/*\r\n     SELECT ESTATUS\r\n     FROM M_FORMULARIOS\r\n     WHERE ID_M_FORMULARIOS = NEW.ID_M_FORMULARIOS\r\n     INTO XESTATUS;\r\n\r\n     IF(:XESTATUS = 'ACT') THEN\r\n     BEGIN\r\n          SELECT ID_M_KOBO_FORMULARIOS\r\n          FROM M_KOBO_FORMULARIOS\r\n          WHERE ID_M_FORMULARIOS = NEW.ID_M_FORMULARIOS AND\r\n                UID = NEW.UID AND\r\n                FUID = NEW.FUID\r\n          INTO NEW.ID_M_KOBO_FORMULARIOS;\r\n\r\n          IF(ROW_COUNT = 0) THEN\r\n          BEGIN\r\n               INSERT\r\n               INTO M_KOBO_FORMULARIOS ( ID_M_FORMULARIOS, UID, FUID ,FUNICO)\r\n               VALUES ( NEW.ID_M_FORMULARIOS, NEW.UID, NEW.FUID, NEW.FUNICO )\r\n               RETURNING ID_M_KOBO_FORMULARIOS\r\n               INTO NEW.ID_M_KOBO_FORMULARIOS;\r\n          END\r\n\r\n\r\n          INSERT\r\n          INTO M_KOBO_RESPUESTAS ( ID_TMP_RESPUESTAS, ID_M_KOBO_FORMULARIOS, ID_M_FORMULARIOS, ID_P_FORMULARIOS, TIPO,\r\n          ROTULO, VALOR_C, VALOR_N, VALOR, REFERENCIA, ESTATUS, UID, FUID)\r\n          VALUES(NEW.ID_TMP_RESPUESTAS, NEW.ID_M_KOBO_FORMULARIOS, NEW.ID_M_FORMULARIOS, NEW.ID_P_FORMULARIOS, NEW.TIPO,\r\n          NEW.ROTULO, NEW.VALOR_C, NEW.VALOR_N, NEW.VALOR, NEW.REFERENCIA, NEW.ESTATUS, NEW.UID, NEW.FUID) RETURNING ID_M_KOBO_RESPUESTAS INTO NEW.ID_M_KOBO_RESPUESTAS;\r\n\r\n     END\r\n--*/\r\nEND"


DECLARE 
     VARIABLE XID_M_KOBO_FORMULARIOS VARCHAR(16);
DECLARE VARIABLE \"ROW_COUNT\" INTEGER;
DECLARE VARIABLE XESTATUS VARCHAR(20);
DECLARE VARIABLE XROTULO VARCHAR(5000);
BEGIN
--/*
     SELECT ESTATUS
     FROM M_FORMULARIOS
     WHERE ID_M_FORMULARIOS = NEW.ID_M_FORMULARIOS
     INTO XESTATUS;

     IF(:XESTATUS = 'ACT') THEN
     BEGIN
          SELECT ID_M_KOBO_FORMULARIOS
          FROM M_KOBO_FORMULARIOS
          WHERE ID_M_FORMULARIOS = NEW.ID_M_FORMULARIOS AND
                UID = NEW.UID AND
                FUID = NEW.FUID
          INTO NEW.ID_M_KOBO_FORMULARIOS;

          IF(ROW_COUNT = 0) THEN
          BEGIN
               INSERT INTO M_KOBO_FORMULARIOS ( ID_M_FORMULARIOS, UID, FUID ,FUNICO)
               VALUES ( NEW.ID_M_FORMULARIOS, NEW.UID, NEW.FUID, NEW.FUNICO )
               RETURNING ID_M_KOBO_FORMULARIOS
               INTO NEW.ID_M_KOBO_FORMULARIOS;
          END

          /*RESPUESTAS DESDE TEMP RECEPTOR MIGRACIN*/
          INSERT INTO M_KOBO_RESPUESTAS ( ID_TMP_RESPUESTAS, ID_M_KOBO_FORMULARIOS, ID_M_FORMULARIOS, ID_P_FORMULARIOS, TIPO,
          ROTULO, VALOR_C, VALOR_N, VALOR, REFERENCIA, ESTATUS, UID, FUID)
          VALUES(NEW.ID_TMP_RESPUESTAS, NEW.ID_M_KOBO_FORMULARIOS, NEW.ID_M_FORMULARIOS, NEW.ID_P_FORMULARIOS, NEW.TIPO,
          NEW.ROTULO, NEW.VALOR_C, NEW.VALOR_N, NEW.VALOR, NEW.REFERENCIA, NEW.ESTATUS, NEW.UID, NEW.FUID) RETURNING ID_M_KOBO_RESPUESTAS INTO NEW.ID_M_KOBO_RESPUESTAS;

          /*PREGUNTA DESDE TEMP RECEPTOR MIGRACIN*/
          INSERT INTO P_FORMULARIOS ( ID_TMP_RESPUESTAS, ID_M_KOBO_FORMULARIOS, ID_M_FORMULARIOS, ID_P_FORMULARIOS, TIPO,
          ROTULO, VALOR_C, VALOR_N, VALOR, REFERENCIA, ESTATUS, UID, FUID)
          VALUES(NEW.ID_TMP_RESPUESTAS, NEW.ID_M_KOBO_FORMULARIOS, NEW.ID_M_FORMULARIOS, NEW.ID_P_FORMULARIOS, NEW.TIPO,
          NEW.ROTULO, NEW.VALOR_C, NEW.VALOR_N, NEW.VALOR, NEW.REFERENCIA, NEW.ESTATUS, NEW.UID, NEW.FUID) RETURNING ID_M_KOBO_RESPUESTAS INTO NEW.ID_M_KOBO_RESPUESTAS;


     END
--*/
END"
