-- M_KOBO_RESPUESTAS_ESTADISTICA ON M_KOBO_RESPUESTAS

BEGIN
--/*
     -- FECHAS
     IF(NEW.ID_P_FORMULARIOS = '001428' ) THEN -- 'FECHA DE LA ALERTA' FORMULARIO 0011
     BEGIN
          UPDATE M_KOBO_FORMULARIOS SET
                 FECHA_ESTADISTICA = NEW.VALOR_F
          WHERE ID_M_KOBO_FORMULARIOS = NEW.ID_M_KOBO_FORMULARIOS;
     END


     IF(NEW.ID_P_FORMULARIOS = '001198' ) THEN --  'FECHA DE ELABORACION ERN' FORMULARIO 0012
     BEGIN
          UPDATE M_KOBO_FORMULARIOS SET
                 FECHA_ESTADISTICA = NEW.VALOR_F
          WHERE ID_M_KOBO_FORMULARIOS = NEW.ID_M_KOBO_FORMULARIOS;
     END

     IF(NEW.ID_P_FORMULARIOS = '0012' ) THEN -- 'FECHA DE REPORTE' FORMULARIO 0013
     BEGIN
          UPDATE M_KOBO_FORMULARIOS SET
                 FECHA_ESTADISTICA = NEW.VALOR_F
          WHERE ID_M_KOBO_FORMULARIOS = NEW.ID_M_KOBO_FORMULARIOS;
     END

     -- LOCALIDAD O UBICACION
     IF(NEW.ID_P_FORMULARIOS = '001433' ) THEN -- 'DEPARTAMENTO' FORMULARIO 0011
     BEGIN
          UPDATE M_KOBO_FORMULARIOS SET
                 DEPARTAMENTO = NEW.XVALOR
          WHERE ID_M_KOBO_FORMULARIOS = NEW.ID_M_KOBO_FORMULARIOS;

     END

     IF(NEW.ID_P_FORMULARIOS = '001203' ) THEN -- 'DEPARTAMENTO' FORMULARIO 0012
     BEGIN
          UPDATE M_KOBO_FORMULARIOS SET
                 DEPARTAMENTO = NEW.XVALOR
          WHERE ID_M_KOBO_FORMULARIOS = NEW.ID_M_KOBO_FORMULARIOS;
     END

     IF(NEW.ID_P_FORMULARIOS = '0017' ) THEN -- 'DEPARTAMENTO' FORMULARIO 0013
     BEGIN
          UPDATE M_KOBO_FORMULARIOS SET
                 DEPARTAMENTO = NEW.XVALOR
          WHERE ID_M_KOBO_FORMULARIOS = NEW.ID_M_KOBO_FORMULARIOS;
     END

     IF(NEW.ID_P_FORMULARIOS = '0011' ) THEN -- 'CODIGO' FORMULARIO 0013
     BEGIN
          UPDATE M_KOBO_FORMULARIOS SET
                 XCODIGO_ALERTA = NEW.XVALOR
          WHERE ID_M_KOBO_FORMULARIOS = NEW.ID_M_KOBO_FORMULARIOS;
     END

     IF(NEW.ID_P_FORMULARIOS = '001197'   ) THEN -- 'CODIGO' FORMULARIO 0012
     BEGIN
          UPDATE M_KOBO_FORMULARIOS SET
                 XCODIGO_ALERTA = NEW.XVALOR
          WHERE ID_M_KOBO_FORMULARIOS = NEW.ID_M_KOBO_FORMULARIOS;
     END

     -- CODIGO DE ALERTA - CLASIFICA COMO VBG  /* ALERTA BASADA EN: - FORMULARIO 0011
     IF(NEW.ID_P_FORMULARIOS = '001473' AND NEW.XVALOR = 'REQUERIMIENTO INDIVIDUAL POR VBG') THEN
     BEGIN
          UPDATE M_KOBO_FORMULARIOS SET
                 XCODIGO_ALERTA = 'VBG-' || XCODIGO_ALERTA
          WHERE ID_M_KOBO_FORMULARIOS = NEW.ID_M_KOBO_FORMULARIOS AND
                XCODIGO_ALERTA NOT LIKE 'VBG-%';
     END
     

     -- PARA UN FORMULARIO DE PERFIL TERRITORIAL SE DEFINE EL DEPARTAMENTO anFYtJMm6iFs55vrnsBtN8
     -- IF((NEW.REFERENCIA LIKE '%departamento%'  OR NEW.REFERENCIA LIKE '%DEPARTAMENTO%') AND NEW.VALOR != '' AND NEW.ID_M_KOBO_FORMULARIOS = 0014240) THEN
     IF((NEW.REFERENCIA LIKE '%departamento%'  OR NEW.REFERENCIA LIKE '%DEPARTAMENTO%') AND NEW.VALOR != '' AND NEW.ID_M_FORMULARIOS = 001121) THEN
     BEGIN
          UPDATE M_KOBO_FORMULARIOS SET
                 DEPARTAMENTO = UPPER(NEW.XVALOR)
          WHERE ID_M_KOBO_FORMULARIOS = NEW.ID_M_KOBO_FORMULARIOS;
     END
    
    -- PARA UN FORMULARIO DE PERFIL TERRITORIAL SE DEFINE EL MUNICIPIO anFYtJMm6iFs55vrnsBtN8
    -- IF((NEW.REFERENCIA LIKE '%municipio%'  OR NEW.REFERENCIA LIKE '%MUNICIPIO%') AND NEW.VALOR != '' AND NEW.ID_M_KOBO_FORMULARIOS = 0014240) THEN
    IF((NEW.REFERENCIA LIKE '%municipio%'  OR NEW.REFERENCIA LIKE '%MUNICIPIO%') AND NEW.VALOR != '' AND (NEW.ID_M_FORMULARIOS = 001121 OR NEW.ID_M_FORMULARIOS = 0014 OR NEW.ID_M_FORMULARIOS = 0011)) THEN
    BEGIN 
        SELECT NOMBRES 
        FROM M_MUNICIPIOS  
        WHERE  CAMPO1 = NEW.XVALOR 
        ROWS 1 
        INTO XMUNICIPIO;
        UPDATE M_KOBO_FORMULARIOS SET
               MUNICIPIO = UPPER(:XMUNICIPIO)
                --MUNICIPIO = UPPER(substring(NEW.XVALOR FROM position ('_' in NEW.XVALOR) + 1 FOR CHAR_LENGTH(NEW.XVALOR)))
        WHERE ID_M_KOBO_FORMULARIOS = NEW.ID_M_KOBO_FORMULARIOS;
    END
--*/
END