select RDB$TRIGGER_NAME, RDB$RELATION_NAME, RDB$TRIGGER_SOURCE from rdb$TRIGGERS where rdb$TRIGGER_NAME = 'TMP_RESPUESTAS_VALOR'

"TRIGGER_NAME": "TMP_RESPUESTAS_VALOR                                                                         ",
            "TABLE_NAME": "TMP_RESPUESTAS                                                                               ",
            
            "TRIGGER_BODY": "AS\r\nDECLARE VARIABLE NOMBRES VARCHAR(10000);\r\nDECLARE VARIABLE OPCIONES VARCHAR(10000);\r\nDECLARE VARIABLE PART VARCHAR(32000);\r\nBEGIN\r\n--/*\r\n   SELECT ID_M_FORMULARIOS, NOMBRES FROM M_FORMULARIOS\r\n   WHERE UID = NEW.FUID INTO NEW.ID_M_FORMULARIOS, :NOMBRES;\r\n\r\n   SELECT first 1\r\n          P_FORMULARIOS.ID_P_FORMULARIOS,\r\n          P_FORMULARIOS.ROTULO\r\n   FROM P_FORMULARIOS\r\n   WHERE ID_M_FORMULARIOS = NEW.ID_M_FORMULARIOS\r\n   AND REFERENCIA = NEW.REFERENCIA INTO\r\n   NEW.ID_P_FORMULARIOS, NEW.ROTULO;\r\n\r\n   IF(new.CAMPO1='*') THEN EXIT;\r\n\r\n   SELECT first 1 OPCIONES FROM P_FORMULARIOS\r\n   WHERE ID_M_FORMULARIOS = NEW.ID_M_FORMULARIOS\r\n   AND REFERENCIA = NEW.REFERENCIA INTO :OPCIONES;\r\n   NEW.VALOR = NEW.VALOR_C;\r\n\r\n   IF(COALESCE(:OPCIONES, '') IS DISTINCT FROM '')THEN\r\n   BEGIN\r\n        SELECT FIRST 1 PART FROM SPLIT(:OPCIONES, ',') WHERE PART LIKE UPPER(NEW.VALOR_C)||'%' INTO :PART;\r\n        IF(:PART IS NOT NULL )THEN\r\n        BEGIN\r\n             SELECT FIRST 1 TRIM(PART) FROM SPLIT(:PART, ':') ORDER BY ID DESC INTO NEW.VALOR;\r\n        END\r\n   END\r\n--*/\r\nEND\r\n\r\n",
            

AS
DECLARE VARIABLE NOMBRES VARCHAR(10000);
DECLARE VARIABLE OPCIONES VARCHAR(10000);
DECLARE VARIABLE PART VARCHAR(32000);
BEGIN
--/*
   SELECT ID_M_FORMULARIOS, NOMBRES FROM M_FORMULARIOS
   WHERE UID = NEW.FUID INTO NEW.ID_M_FORMULARIOS, :NOMBRES;

   SELECT first 1
          P_FORMULARIOS.ID_P_FORMULARIOS,
          P_FORMULARIOS.ROTULO
   FROM P_FORMULARIOS
   WHERE ID_M_FORMULARIOS = NEW.ID_M_FORMULARIOS
   AND REFERENCIA = NEW.REFERENCIA INTO
   NEW.ID_P_FORMULARIOS, NEW.ROTULO;

   IF(new.CAMPO1='*') THEN EXIT;

   SELECT first 1 OPCIONES FROM P_FORMULARIOS
   WHERE ID_M_FORMULARIOS = NEW.ID_M_FORMULARIOS
   AND REFERENCIA = NEW.REFERENCIA INTO :OPCIONES;
   NEW.VALOR = NEW.VALOR_C;

   IF(COALESCE(:OPCIONES, '') IS DISTINCT FROM '')THEN
   BEGIN
        SELECT FIRST 1 PART FROM SPLIT(:OPCIONES, ',') WHERE PART LIKE UPPER(NEW.VALOR_C)||'%' INTO :PART;
        IF(:PART IS NOT NULL )THEN
        BEGIN
             SELECT FIRST 1 TRIM(PART) FROM SPLIT(:PART, ':') ORDER BY ID DESC INTO NEW.VALOR;
        END
   END
--*/
END

",
