-- M_KOBO_FORMULARIOS_CODIGO on update m_kobo_formularios

BEGIN
--/*
     IF (
          (NEW.ID_M_FORMULARIOS = '0011' AND NEW.DEPARTAMENTO IS NOT NULL AND NEW.PREFIJO_ALERTA IS NOT NULL AND NEW.XCODIGO_ALERTA IS NULL)
          OR
          (NEW.ID_M_FORMULARIOS = '0014' AND NEW.DEPARTAMENTO IS NOT NULL AND NEW.PREFIJO_ALERTA IS NOT NULL AND NEW.XCODIGO_ALERTA IS NULL)
      ) THEN
     BEGIN

          SELECT COALESCE(CODIGO_ALERTA,0) + 1
          FROM M_KOBO_FORMULARIOS
          WHERE XCODIGO_ALERTA NOT LIKE 'RT-%'
          ORDER BY CODIGO_ALERTA DESC
          ROWS 1
          INTO CODIGO_ALERTA;

          XMUNICIPIO = NEW.MUNICIPIO;


     -- PERSONAS EN RIESGO NNAJ = NNAJ- Y SI ES PERSONAS EN RIESGO - ADULTOS = PR

          --EXCEPTION E_DEBUG 'X-> ' || :XVBG;

          IF(NEW.DEPARTAMENTO IS NOT NULL AND COALESCE(:XMUNICIPIO,'') IS DISTINCT FROM '') THEN
          BEGIN

               VALIDLETRADEP = COALESCE(NEW.DEPARTAMENTO,'.1.');
               LETRADEP = SUBSTRING(VALIDLETRADEP from 1 for 2);
               VALIDLETRAMUN = COALESCE(:XMUNICIPIO,'.2.');
               LETRAMUN = SUBSTRING(VALIDLETRAMUN from 1 for 2);
               
               XCODIGO_ALERTA = COALESCE(NEW.PREFIJO_ALERTA,'') || COALESCE(LETRADEP,'') || COALESCE(LETRAMUN,'') || '-' || LPAD(CAST(COALESCE(:CODIGO_ALERTA,'.3.') AS VARCHAR(20)),'4','0') || '.1';
               XCODIGO_ALERTA = REPLACE(:XCODIGO_ALERTA,' ','');

               UPDATE M_KOBO_FORMULARIOS SET
                      CODIGO_ALERTA = :CODIGO_ALERTA,
                      MUNICIPIO = :XMUNICIPIO,
                      XCODIGO_ALERTA = :XCODIGO_ALERTA
               WHERE ID_M_KOBO_FORMULARIOS = NEW.ID_M_KOBO_FORMULARIOS;
          END
     END

     
     IF(NEW.ID_M_FORMULARIOS = 1121 AND NEW.DEPARTAMENTO IS NOT NULL AND NEW.PREFIJO_ALERTA IS NOT NULL AND NEW.XCODIGO_ALERTA IS NULL ) THEN
     BEGIN

          SELECT COALESCE(CODIGO_ALERTA,0) + 1
          FROM M_KOBO_FORMULARIOS
          WHERE XCODIGO_ALERTA LIKE 'RT-%'
          ORDER BY CODIGO_ALERTA DESC
          ROWS 1
          INTO CODIGO_ALERTA;

          XMUNICIPIO = NEW.MUNICIPIO;

 

          IF(NEW.DEPARTAMENTO IS NOT NULL AND COALESCE(:XMUNICIPIO,'') IS DISTINCT FROM '') THEN
          BEGIN

               VALIDLETRADEP = COALESCE(NEW.DEPARTAMENTO,'.1.');
               LETRADEP = SUBSTRING(VALIDLETRADEP from 1 for 2);
               VALIDLETRAMUN = COALESCE(:XMUNICIPIO,'.2.');
               LETRAMUN = SUBSTRING(VALIDLETRAMUN from 1 for 2);
               
               XCODIGO_ALERTA = COALESCE(NEW.PREFIJO_ALERTA,'') || COALESCE(LETRADEP,'') || COALESCE(LETRAMUN,'') || '-' || COALESCE(:CODIGO_ALERTA, 0) || '.1';
               XCODIGO_ALERTA = REPLACE(:XCODIGO_ALERTA,' ','');

               UPDATE M_KOBO_FORMULARIOS SET
                      CODIGO_ALERTA = :CODIGO_ALERTA,
                      MUNICIPIO = :XMUNICIPIO,
                      XCODIGO_ALERTA = COALESCE(:XCODIGO_ALERTA, 'Error al generar')
               WHERE ID_M_KOBO_FORMULARIOS = NEW.ID_M_KOBO_FORMULARIOS;
          END
     END
--*/
END