-- M_KOBO_FORMULARIOS_CODIGO on update m_kobo_formularios
            "TRIGGER_BODY": "AS\r\nDECLARE VARIABLE XVALOR VARCHAR(1000);\r\nDECLARE VARIABLE XCODIGO_ALERTA VARCHAR(60);\r\nDECLARE VARIABLE CODIGO_ALERTA VARCHAR(60);\r\nDECLARE VARIABLE XMUNICIPIO VARCHAR(60);\r\nDECLARE VARIABLE XVBG VARCHAR(60);\r\nDECLARE VARIABLE VALIDLETRADEP VARCHAR(60);\r\nDECLARE VARIABLE LETRADEP VARCHAR(60);\r\nDECLARE VARIABLE VALIDLETRAMUN VARCHAR(60);\r\nDECLARE VARIABLE LETRAMUN VARCHAR(60);\r\nBEGIN\r\n--/*\r\n     IF (NEW.ID_M_FORMULARIOS = '0011' AND NEW.DEPARTAMENTO IS NOT NULL AND NEW.PREFIJO_ALERTA IS NOT NULL AND NEW.XCODIGO_ALERTA IS NULL ) THEN\r\n     BEGIN\r\n\r\n          SELECT COALESCE(CODIGO_ALERTA,0) + 1\r\n          FROM M_KOBO_FORMULARIOS\r\n          ORDER BY CODIGO_ALERTA DESC\r\n          ROWS 1\r\n          INTO CODIGO_ALERTA;\r\n\r\n          XMUNICIPIO = NEW.MUNICIPIO;\r\n\r\n\r\n-- PERSONAS EN RIESGO NNAJ = NNAJ- Y SI ES PERSONAS EN RIESGO - ADULTOS = PR\r\n\r\n          --EXCEPTION E_DEBUG 'X-> ' || :XVBG;\r\n\r\n          IF(NEW.DEPARTAMENTO IS NOT NULL AND COALESCE(:XMUNICIPIO,'') IS DISTINCT FROM '') THEN\r\n          BEGIN\r\n\r\n               VALIDLETRADEP = COALESCE(NEW.DEPARTAMENTO,'.1.');\r\n               LETRADEP = SUBSTRING(VALIDLETRADEP from 1 for 2);\r\n               VALIDLETRAMUN = COALESCE(:XMUNICIPIO,'.2.');\r\n               LETRAMUN = SUBSTRING(VALIDLETRAMUN from 1 for 2);\r\n               \r\n               XCODIGO_ALERTA = COALESCE(NEW.PREFIJO_ALERTA,'') || COALESCE(LETRADEP,'') || COALESCE(LETRAMUN,'') || '-' || LPAD(CAST(COALESCE(:CODIGO_ALERTA,'.3.') AS VARCHAR(20)),'4','0') || '.1';\r\n               XCODIGO_ALERTA = REPLACE(:XCODIGO_ALERTA,' ','');\r\n\r\n               UPDATE M_KOBO_FORMULARIOS SET\r\n                      CODIGO_ALERTA = :CODIGO_ALERTA,\r\n                      MUNICIPIO = :XMUNICIPIO,\r\n                      XCODIGO_ALERTA = :XCODIGO_ALERTA\r\n               WHERE ID_M_KOBO_FORMULARIOS = NEW.ID_M_KOBO_FORMULARIOS;\r\n          END\r\n     END\r\n--*/\r\nEND",


CREATE TRIGGER M_KOBO_FORMULARIOS_CODIGO FOR M_KOBO_FORMULARIOS
ACTIVE AFTER UPDATE
POSITION 3
AS
DECLARE VARIABLE XVALOR VARCHAR(1000);
DECLARE VARIABLE XCODIGO_ALERTA VARCHAR(60);
DECLARE VARIABLE CODIGO_ALERTA VARCHAR(60);
DECLARE VARIABLE XMUNICIPIO VARCHAR(60);
DECLARE VARIABLE XVBG VARCHAR(60);
DECLARE VARIABLE VALIDLETRADEP VARCHAR(60);
DECLARE VARIABLE LETRADEP VARCHAR(60);
DECLARE VARIABLE VALIDLETRAMUN VARCHAR(60);
DECLARE VARIABLE LETRAMUN VARCHAR(60);
BEGIN
--/*
     IF ((NEW.ID_M_FORMULARIOS = '0011' OR NEW.ID_M_FORMULARIOS = '0014') AND NEW.DEPARTAMENTO IS NOT NULL AND NEW.PREFIJO_ALERTA IS NOT NULL AND NEW.XCODIGO_ALERTA IS NULL ) THEN
     BEGIN

          SELECT COALESCE(CODIGO_ALERTA,0) + 1
          FROM M_KOBO_FORMULARIOS
          WHERE XCODIGO_ALERTA NOT LIKE 'RT-%'
          ORDER BY CODIGO_ALERTA DESC
          ROWS 1
          INTO CODIGO_ALERTA;

          XMUNICIPIO = NEW.MUNICIPIO;


-- PERSONAS EN RIESGO NNAJ = NNAJ- Y SI ES PERSONAS EN RIESGO - ADULTOS = PR

          --EXCEPTION E_DEBUG 'X-> ' || :XVBG;

          IF(NEW.DEPARTAMENTO IS NOT NULL AND COALESCE(:XMUNICIPIO,'') IS DISTINCT FROM '') THEN
          BEGIN

               VALIDLETRADEP = COALESCE(NEW.DEPARTAMENTO,'.1.');
               LETRADEP = SUBSTRING(VALIDLETRADEP from 1 for 2);
               VALIDLETRAMUN = COALESCE(:XMUNICIPIO,'.2.');
               LETRAMUN = SUBSTRING(VALIDLETRAMUN from 1 for 2);

               XCODIGO_ALERTA = COALESCE(NEW.PREFIJO_ALERTA,'') || COALESCE(LETRADEP,'') || COALESCE(LETRAMUN,'') || '-' || LPAD(CAST(COALESCE(:CODIGO_ALERTA,'.3.') AS VARCHAR(20)),'4','0') || '.1';
               XCODIGO_ALERTA = REPLACE(:XCODIGO_ALERTA,' ','');
               XCODIGO_ALERTA = UPPER(:XCODIGO_ALERTA);

               UPDATE M_KOBO_FORMULARIOS SET
                      CODIGO_ALERTA = :CODIGO_ALERTA,
                      MUNICIPIO = :XMUNICIPIO,
                      XCODIGO_ALERTA = :XCODIGO_ALERTA
               WHERE ID_M_KOBO_FORMULARIOS = NEW.ID_M_KOBO_FORMULARIOS;
          END
     END
     
     IF(NEW.ID_M_FORMULARIOS = 1121 AND NEW.DEPARTAMENTO IS NOT NULL AND NEW.PREFIJO_ALERTA IS NOT NULL AND NEW.XCODIGO_ALERTA IS NULL ) THEN
     BEGIN

          SELECT COALESCE(CODIGO_ALERTA,0) + 1
          FROM M_KOBO_FORMULARIOS
          WHERE XCODIGO_ALERTA LIKE 'RT-%'
          ORDER BY CODIGO_ALERTA DESC
          ROWS 1
          INTO CODIGO_ALERTA;

          XMUNICIPIO = NEW.MUNICIPIO;



          IF(NEW.DEPARTAMENTO IS NOT NULL AND COALESCE(:XMUNICIPIO,'') IS DISTINCT FROM '') THEN
          BEGIN

               VALIDLETRADEP = COALESCE(NEW.DEPARTAMENTO,'.1.');
               LETRADEP = SUBSTRING(VALIDLETRADEP from 1 for 2);
               VALIDLETRAMUN = COALESCE(:XMUNICIPIO,'.2.');
               LETRAMUN = SUBSTRING(VALIDLETRAMUN from 1 for 2);

               XCODIGO_ALERTA = COALESCE(NEW.PREFIJO_ALERTA,'') || COALESCE(LETRADEP,'') || COALESCE(LETRAMUN,'') || '-' || COALESCE(:CODIGO_ALERTA, 0) || '.1';
               XCODIGO_ALERTA = REPLACE(:XCODIGO_ALERTA,' ','');
               XCODIGO_ALERTA = UPPER(:XCODIGO_ALERTA);

               UPDATE M_KOBO_FORMULARIOS SET
                      CODIGO_ALERTA = :CODIGO_ALERTA,
                      MUNICIPIO = :XMUNICIPIO,
                      XCODIGO_ALERTA = COALESCE(:XCODIGO_ALERTA, 'Error al generar')
               WHERE ID_M_KOBO_FORMULARIOS = NEW.ID_M_KOBO_FORMULARIOS;
          END
     END
--*/
END