SET TERM ^ ;

CREATE TRIGGER TMP_RESPUESTAS_VALOR FOR TMP_RESPUESTAS
ACTIVE BEFORE INSERT OR UPDATE
POSITION 2
AS
DECLARE VARIABLE NOMBRES VARCHAR(10000);
DECLARE VARIABLE OPCIONES VARCHAR(10000);
DECLARE VARIABLE PART VARCHAR(32000);
BEGIN
--/*
   SELECT ID_M_FORMULARIOS, NOMBRES FROM M_FORMULARIOS
   WHERE UID = NEW.FUID INTO NEW.ID_M_FORMULARIOS, :NOMBRES;

   SELECT first 1
          P_FORMULARIOS.ID_P_FORMULARIOS,
          P_FORMULARIOS.ROTULO
   FROM P_FORMULARIOS
   WHERE ID_M_FORMULARIOS = NEW.ID_M_FORMULARIOS
   AND REFERENCIA = NEW.REFERENCIA INTO
   NEW.ID_P_FORMULARIOS, NEW.ROTULO;

   IF(new.CAMPO1='*') THEN EXIT;

   SELECT first 1 OPCIONES FROM P_FORMULARIOS
   WHERE ID_M_FORMULARIOS = NEW.ID_M_FORMULARIOS
   AND REFERENCIA = NEW.REFERENCIA INTO :OPCIONES;
   NEW.VALOR = NEW.VALOR_C;

   IF(COALESCE(:OPCIONES, '') IS DISTINCT FROM '')THEN
   BEGIN
        SELECT FIRST 1 PART FROM SPLIT(:OPCIONES, ',') WHERE PART LIKE UPPER(NEW.VALOR_C)||'%' INTO :PART;
        IF(:PART IS NOT NULL )THEN
        BEGIN
             SELECT FIRST 1 TRIM(PART) FROM SPLIT(:PART, ':') ORDER BY ID DESC INTO NEW.VALOR;
        END
   END
--*/
END^

SET TERM ; 