            "RDB$VIEW_SOURCE": "\r\nSELECT\r\nI_MENU_GRUP.ID_I_MENU_GRUP,\r\nI_MENU_GRUP.ID_M_MENU,\r\nI_MENU_GRUP.ID_M_GRUPOS,\r\nI_MENU_GRUP.ID_M_USUARIOS,\r\nM_USUARIOS.NOMBRE_COMPLETO AS NOMBRE_USUARIO,\r\nI_MENU_GRUP.FECHA,\r\nM_GRUPOS.NOMBRES AS NOMBRE_GRUPO,\r\nM_MENU.ROTULO,\r\nI_MENU_GRUP.POSICION,\r\nIIF(I_MENU_GRUP.URL IS NOT NULL,'/'||LOWER((SELECT SISTEMA FROM CONFIGURACION ))||'/'||I_MENU_GRUP.URL,NULL) URL,\r\nM_MENU.PARAMS,\r\nM_MENU.TARGET,\r\nM_MENU.ICONO,\r\nM_MENU.ID_PADRE\r\nFROM  I_MENU_GRUP\r\nINNER JOIN M_MENU ON (I_MENU_GRUP.ID_M_MENU = M_MENU.ID_M_MENU)\r\nLEFT JOIN M_GRUPOS ON (I_MENU_GRUP.ID_M_GRUPOS = M_GRUPOS.ID_M_GRUPOS)\r\nLEFT JOIN M_USUARIOS ON (I_MENU_GRUP.ID_M_USUARIOS = M_USUARIOS.ID_M_USUARIO)\r\n\r\n"
SELECT
    I_MENU_GRUP.ID_I_MENU_GRUP,
    I_MENU_GRUP.ID_M_MENU,
    I_MENU_GRUP.ID_M_GRUPOS,
    I_MENU_GRUP.ID_M_USUARIOS,
    M_USUARIOS.NOMBRE_COMPLETO AS NOMBRE_USUARIO,
    I_MENU_GRUP.FECHA,
    M_GRUPOS.NOMBRES AS NOMBRE_GRUPO,
    M_MENU.ROTULO,
    I_MENU_GRUP.POSICION,
    IIF(I_MENU_GRUP.URL IS NOT NULL,'/'||LOWER((SELECT SISTEMA FROM CONFIGURACION ))||'/'||I_MENU_GRUP.URL,NULL) URL,
    M_MENU.PARAMS,
    M_MENU.TARGET,
    M_MENU.ICONO,
    M_MENU.ID_PADRE
FROM  
    I_MENU_GRUP
INNER JOIN M_MENU ON (I_MENU_GRUP.ID_M_MENU = M_MENU.ID_M_MENU)
LEFT JOIN M_GRUPOS ON (I_MENU_GRUP.ID_M_GRUPOS = M_GRUPOS.ID_M_GRUPOS)
LEFT JOIN M_USUARIOS ON (I_MENU_GRUP.ID_M_USUARIOS = M_USUARIOS.ID_M_USUARIO)
